### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by anton-kazlouski** [Hrant1997/test-django-vue#1]
Hello! Thanks for your time and efforts. Below you can find some thoughts regarding the homework.

BE
1. There is no need to include pycache, usually code repository is not the right place for db dump
2. makemigrations should not be required step as all migrations must be in place already
3. No requirements file
4. Readme is not really well documented
5. It would be nice to see more complex db schema
6. There is shipping address (start) and billing address which is not always equal to the delivery address (finish)
7. Prices limits are arguable, but decimal field is definitely a plus.
8. Here and there I can see that formatting is a bit odd or doesn't follow PEP8, grammar mistakes.
9. The tests are done well. Nice to see advanced usage of APITestCase, precisely using of fixtures.
10. ShipmentViewSet is short which is good in this case as there is no any custom logic. 

FE
1. It would be nice to see more user-friendly design
2. No error handling. User should be notified about errors.
3. Redundant logging to console
4. CreateUpdateShipmentModal.vue could be just Shipment.vue, it is possible to identify whether put or post method should be used by checking shipment.id. Thus, mode prop is redundant
5. No validation of input data
6. I like that the structure is simple and straightforward, although there is some room for improvements

Summary:
There is definitely potential for a good homework. In order to proceed to our customer I would propose to address issues outlined above, probably you'll find more. Otherwise, I'm pretty sure that they won't be satisfied with this result.

Please do not hesitate to request clarification on my feedback.

**Comment by Hrant1997** [comment]
Hi Anton
Thanks for detailed feedback
Let me quickly go throughout all points and fix everything
I will resend the task asap.

вт, 23 авг. 2022 г. в 20:16, anton-kazlouski ***@***.***>:

**Comment by Hrant1997** [comment]
Hi Anton
Hope you are doing well
Before I'll fix points I wanted to clarify one thing
Do you think that I had to finish the task with all that points in 4-5
hours?

вт, 23 авг. 2022 г. в 21:53, Hrant Yepiskoposyan <
***@***.***>:

**Comment by anton-kazlouski** [comment]
Hi Hrant!
It’s a good question. I understand that for some it can take more time for others less. We are aware that candidates can frustrate doing test task and would prefer having an interview, but this the requirement of our client. We had seen a few strong homeworks, however I can’t be sure if a candidate actually spend 4-5 hours.

Anton Kazlouski
Software Engineer

[X] ***@***.******@***.***>

[X] +48 573 238 757

[X]

This email and any files transmitted are confidential and are intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Solbeg accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing.

On 24 Aug 2022, at 08:23, Hrant1997 ***@***.******@***.***>> wrote:


Hi Anton
Hope you are doing well
Before I'll fix points I wanted to clarify one thing
Do you think that I had to finish the task with all that points in 4-5
hours?

вт, 23 авг. 2022 г. в 21:53, Hrant Yepiskoposyan <
***@***.***>:

**Comment by anton-kazlouski** [comment]
OK, thank you!


Anton Kazlouski
Software Engineer

[X] ***@***.******@***.***>

[X] +48 573 238 757

[X]

This email and any files transmitted are confidential and are intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Solbeg accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing.

On 23 Aug 2022, at 19:53, Hrant1997 ***@***.******@***.***>> wrote:


Hi Anton
Thanks for detailed feedback
Let me quickly go throughout all points and fix everything
I will resend the task asap.

вт, 23 авг. 2022 г. в 20:16, anton-kazlouski ***@***.***>:

**Comment by Hrant1997** [comment]
Hi Anton.
I wanted to let you know as I already pushed the new version of code, so
you can already have a look.

Regards,
Hrant


ср, 24 авг. 2022 г. в 10:23, Hrant Yepiskoposyan <
***@***.***>:

**Comment by anton-kazlouski** [comment]
Thanks for the updates! We will proceed to our client.
